### ISSUE TITLE
Project Vision Statement

### ISSUE THREAD

**Issue by Fondestjoel** [MozillaFestival/open-leaders-7#108]
I'm working with creatives and tech enthusiasts to make teachers in Nigeria digitally-literate so that they can transform learning outcomes in classrooms.

**Comment by abbycabs** [comment]
Hey @Fondestjoel - you should comment on your other issues https://github.com/MozillaFestival/open-leaders-7/issues/11 instead of creating a new one for your vision statement!

Closing this for now

**Comment by Fondestjoel** [comment]
> Hey @Fondestjoel - you should comment on your other issues #11 instead of creating a new one for your vision statement!
> 
> Closing this for now

Thank you Acabunoc for the correction.
