### ISSUE TITLE
NeuroNetwork

### ISSUE THREAD

**Issue by hannahblair** [MozillaFestival/open-leaders-7#84]
Project Lead: hannahblair

Mentor: Faye Tandog

Welcome to OL7, Cohort A! This issue will be used to track your project and progress during the program. Please use this checklist over the next few weeks as you start Open Leadership Training :tada:.

***

Before Week 1 (Jan 29): Your first mentorship call
- [x] Complete the OLF self-assessment ([online](https://mzl.la/olf-online-assessment), [printable](https://mzl.la/olf-self-assessment)). If you're a group, each teammate should complete this assessment individually. This is here to help you set your own personal goals during the program. No need to share your results, but be ready to share your thoughts with your mentor.
- [x] Make sure you know when and how you'll be meeting with your mentor.

Before Week 2 (Feb 5): First Cohort Call (Open by Design)
- [x] Complete Assignment ['Write Your Vision or Mission Statement'](https://mozilla.github.io/open-leadership-training-series/articles/introduction-to-open-leadership/stating-your-project-vision/). Leave a comment on this issue with your draft vision statement & be ready to share this on the call.
- [x] Watch ['Mozilla & Working Open'](https://youtu.be/quKdaqlR_9w).
- [x] Check the [Syllabus](https://mzl.la/ol7-syllabus) for notes and connection info for all the cohort calls.

Before Week 3 (Feb 12): Mentorship call
- [ ] Look up two other projects and comment on their issues with feedback on their vision statement.
- [x] Complete your Open Canvas ([instructions](https://mozilla.github.io/open-leadership-training-series/articles/opening-your-project/develop-an-open-project-strategy-with-open-canvas/), [canvas](https://goo.gl/to6PYn)). Comment on this issue with a link to your canvas.
- [ ] [Start your Roadmap](https://mozilla.github.io/open-leadership-training-series/articles/opening-your-project/start-your-project-roadmap/). Comment on this issue with your draft Roadmap.

Before Week 4 (Feb 19): Cohort Call (Build for Understanding)
- [ ] Look up two other projects and comment on their issues with feedback on their open canvas.
- [ ] [Pick an open license](https://mozilla.github.io/open-leadership-training-series/articles/get-your-project-online/sharing-your-work-in-the-open/) for the work you're doing during the program.
- [ ] Use your canvas to [start writing a README](https://mozilla.github.io/open-leadership-training-series/articles/opening-your-project/write-a-great-project-readme/), or landing page, for your project. Link to your README in a comment on this issue.

Week 5 and more
- [ ] Create a repository for your project. New to GitHub? You can [fork our templates](https://mozilla.github.io/global-sprint/project-lead-guide/templates/).
- [ ] Add [Contributing Guidlines](https://mozilla.github.io/open-leadership-training-series/articles/building-communities-of-contributors/write-contributor-guidelines/)
- [ ] Add a [Code of Conduct](https://mozilla.github.io/open-leadership-training-series/articles/building-communities-of-contributors/write-a-code-of-conduct/)
- [ ] [Submit your project to Mozilla Pulse](https://www.mozillapulse.org/add), add the tag `#mozsprint`
- [ ] Invite new contributors to into your work!

This issue is here to help you keep track of work as you start Open Leaders. Please refer to the [OL7 Syllabus](https://mzl.la/ol7-syllabus) for more detailed weekly notes and assignments past week 4.

**Comment by hannahblair** [comment]
Canvas: https://docs.google.com/presentation/d/1hGdTCdSwIftC5duqvTjVyK8ffMH9MmnWRMq9be8yuWc/edit?usp=sharing

**Comment by hannahblair** [comment]
Vision:

I’m working with supporters, contributors, and companies who need career-driven neurodiversity to teach career development skills and share hiring opportunities tailored to particular needs to neurodiverse individuals so that they can improve neurodiversity within working environments. 

I’m working open because I believe there is a responsibility in us all to help other people who need support to be successful. Diversity is so important in our working culture, and when they win, so do we.

**Comment by hannahblair** [comment]
Roadmap Draft:

Timeline:

1) Finish Mozilla Course 
2) Create traction, community and advertise launch
3) Launch an online landing page to register interested users
4) Start building NeuroNetwork web app 
5) Create partnerships with Deutsche Bank and Microsoft
6) Launch!

**Comment by jmtaylor86** [comment]
> Canvas: https://docs.google.com/presentation/d/1hGdTCdSwIftC5duqvTjVyK8ffMH9MmnWRMq9be8yuWc/edit?usp=sharing

Your project sounds great! Over time, do you anticipate using the network to reach out to companies without existing neurodiversity initiatives to share strategies and best practices and encourage their participation?
